//auth.js constants
export const RECEIVE_ACCESS_TOKEN = 'RECEIVE_ACCESS_TOKEN';
export const RECEIVE_USERNAME = 'RECEIVE_USERNAME';
export const RECEIVE_FOLLOWING = 'RECEIVE_FOLLOWING';
export const RECEIVE_PLAYLISTS = 'RECEIVE_PLAYLISTS';
export const RECEIVE_TRACKS_FROM_PLAYLIST = 'RECEIVE_TRACKS_FROM_PLAYLIST';
export const RECEIVE_ARTISTS_TOP_TRACKS = 'RECEIVE_ARTISTS_TOP_TRACKS';
export const RECEIVE_SUCCESS = 'RECEIVE_SUCCESS';
export const RECEIVE_FAILURE = 'RECEIVE_FAILURE';
export const RECEIVE_NEW_PLAYLIST = 'RECEIVE_NEW_PLAYLIST';
export const CHANGE_WIDTH_AND_HEIGHT = 'CHANGE_WIDTH_AND_HEIGHT';
export const CHANGE_IS_MOBILE = 'CHANGE_IS_MOBILE';
export const IS_FOLLOWING_DW = 'IS_FOLLOWING_DW';
