//auth.js constants
export const RECEIVE_ACCESS_TOKEN = 'RECEIVE_ACCESS_TOKEN';
export const RECEIVE_USERNAME = 'RECEIVE_USERNAME';
export const RECEIVE_FOLLOWING = 'RECEIVE_FOLLOWING';
export const RECEIVE_PLAYLISTS = 'RECEIVE_PLAYLISTS';
export const RECEIVE_TRACKS_FROM_PLAYLIST = 'RECEIVE_TRACKS_FROM_PLAYLIST';
export const RECEIVE_ARTISTS_TOP_TRACKS = 'RECEIVE_ARTISTS_TOP_TRACKS';
